<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="user-PC" ignored="0" name="Test" tests="7" failures="1" timestamp="2020-08-12T20:29:58 IST" time="25.211" errors="0">
  <testcase name="getTitle_NegativeTest" time="0.48" classname="emicalculator.Test.NegativeTestClass"/>
  <testcase name="verifybutton_NegativeTest" time="0.083" classname="emicalculator.Test.NegativeTestClass"/>
  <testcase name="selectLoanType_NegativeTest" time="3.175" classname="emicalculator.Test.NegativeTestClass"/>
  <testcase name="selectamount_NegativeTest" time="3.293" classname="emicalculator.Test.NegativeTestClass"/>
  <testcase name="selectInterestRate_NegativeTest" time="3.913" classname="emicalculator.Test.NegativeTestClass">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
at emicalculator.Test.NegativeTestClass.selectInterestRate_NegativeTest(NegativeTestClass.java:112)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- selectInterestRate_NegativeTest -->
  <testcase name="selectTenure_NegativeTest" time="3.336" classname="emicalculator.Test.NegativeTestClass"/>
  <testcase name="screenshot_NegativeTest" time="0.409" classname="emicalculator.Test.NegativeTestClass"/>
</testsuite> <!-- Test -->
